apiVersion: pipecd.dev/v1beta1
kind: Application
spec:
  name: opentofu-demo-app

  plugins:
    opentofu:
      - name: opentofu
        with:
          openTofuVersion: "1.9.1"
          workspace: default         
          commandFlags:
            plan:
              - "-no-color"
              - "-input=false"

  pipeline:
    stages:
      - name: OPENTOFU_PLAN
        with:
          exitOnNoChanges: true

  planner:
    alwaysUsePipeline: true
