apiVersion: pipecd.dev/v1beta1
kind: Application
spec:
  name: aws-opentofu-app
  labels:
    env: dev
    team: devops
    platform: aws
  git:
    repoID: tofu-example
    path: terraform-dev
    branch: main
  kind: PLUGIN
  plugins:
    opentofu:
      input:
        version: "1.9.1"
        config: "main.tf"
        workingDir: "."
        init: true
  description: "OpenTofu application for infrastructure deployment."
