apiVersion: pipecd.dev/v1beta1
#kind: TerraformApp
kind: KUBERNETES1234
spec:
  name: aws-opentofu-app
  labels:
    env: dev
    team: devops
  git:
    repoID: tofu-example
    path: terraform-dev           # ✅ Must match folder name where this file lives
    branch: main
  input:
    terraformVersion: 1.9.1
    tfCommand: "apply"            # ✅ Required: what action to perform
    backend:
      type: s3
      config:
        bucket: "tofu-example-state"
        key: "terraform.tfstate"
        region: "us-east-1"
        encrypt: true
        dynamodb_table: "tofu-example-locks"
    variables:
      aws_region: "us-east-1"
      bucket_name: "tofu-example-bucket-123"
      environment: "dev"
  encryption:
    encryptedSecrets:
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    decryptionTargets:
      - "credentials/aws"
  description: |
    OpenTofu application for infrastructure deployment.
