apiVersion: pipecd.dev/v1beta1
kind: Application
spec:
  name: aws-opentofu-app
  git:
    repoID: tofu-example
    path: terraform-dev
    branch: main
  kind: PLUGIN
  plugins:
    opentofu:
      input:
        version: "1.9.1"
        config: "main.tf"
        workingDir: "terraform-dev" 
        env:
          - TF_VAR_aws_region=us-east-1
          - TF_VAR_bucket_name=tofu-example-bucket-123
          - TF_VAR_environment=dev
        init: true
      quickSync:
        autoApprove: true
