apiVersion: pipecd.dev/v1beta1
kind: Application
spec:
  name: opentofu-demo-app

  plugins:
    opentofu:
      openTofuVersion: "1.9.1"
      workspace: default         
      commandFlags:
        plan:
          - "-no-color"
          - "-input=false"
        # apply:
        #   - "-auto-approve"

  pipeline:
    stages:
      - name: OPENTOFU_PLAN
        with:
          exitOnNoChanges: true
      - name: OPENTOFU_APPLY
        # with:
        #   autoApprove: true

  planner:
    alwaysUsePipeline: true
