apiVersion: pipecd.dev/v1beta1
kind: Application
spec:
  name: aws-opentofu-app
  labels:
    env: dev
    team: devops
    platform: aws
  git:
    repoID: tofu-example
    path: terraform-dev
    branch: main
  kind: PLUGIN
  plugins:
    opentofu:
      input:
        # Version of OpenTofu to use
        version: "1.9.1"
        # List of OpenTofu configuration files
        configs:
          - main.tf
        # Working directory for OpenTofu commands
        workingDir: "."
        # Environment variables for OpenTofu
        env:
          - TF_VAR_aws_region=us-east-1
          - TF_VAR_bucket_name=tofu-example-bucket-123
          - TF_VAR_environment=dev
        # Automatically run terraform init
        init: true
      # Configuration for quick sync
      quickSync:
        autoApprove: true
      # Which resources should be considered as the main resources
      resources:
        - type: aws_s3_bucket
          name: example
      # The label will be configured to variant manifests
      variantLabel:
        key: environment
        value: dev
  eventWatcher:
    - matcher:
        name: tofu-config-update
      handler:
        type: GIT_UPDATE
        config:
          replacements:
            - file: main.tf
              yamlField: $.resource.aws_s3_bucket.example.bucket
  encryption:
    encryptedSecrets:
      awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
      awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    decryptionTargets:
      - "credentials/aws"
  description: |
    OpenTofu application for infrastructure deployment.
