name: 'OpenTofu CI'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: 'Validate OpenTofu'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install OpenTofu
      run: |
        wget https://github.com/opentofu/opentofu/releases/download/v1.9.1/tofu_1.9.1_386.deb
        sudo dpkg -i tofu_1.9.1_386.deb
        rm tofu_1.9.1_386.deb

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: OpenTofu Init
      run: tofu init

    - name: OpenTofu Plan
      run: tofu plan
      if: github.event_name == 'pull_request'

