name: 'OpenTofu CI'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: 'Validate OpenTofu'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download OpenTofu .deb Package
      run: |
        wget https://github.com/opentofu/opentofu/releases/download/v1.9.1/tofu_1.9.1_amd64.deb
        wget https://github.com/opentofu/opentofu/releases/download/v1.9.1/tofu_1.9.1_SHA256SUMS
        wget https://github.com/opentofu/opentofu/releases/download/v1.9.1/tofu_1.9.1_SHA256SUMS.sig

    - name: Verify Checksum
      run: |
        sha256sum -c --ignore-missing tofu_1.9.1_SHA256SUMS | grep tofu_1.9.1_amd64.deb

    - name: Install OpenTofu
      run: |
        sudo dpkg -i tofu_1.9.1_amd64.deb
        tofu --version
        rm tofu_1.9.1_amd64.deb tofu_1.9.1_SHA256SUMS tofu_1.9.1_SHA256SUMS.sig

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: OpenTofu Init
      run: tofu init

    - name: OpenTofu Plan
      run: tofu plan
      if: github.event_name == 'pull_request'