name: 'OpenTofu CI'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: 'Validate OpenTofu'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg

    - name: Add OpenTofu GPG Key
      run: |
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://get.opentofu.org/opentofu.gpg | sudo tee /etc/apt/keyrings/opentofu.gpg >/dev/null
        curl -fsSL https://packages.opentofu.org/opentofu/tofu/gpgkey | sudo gpg --no-tty --batch --dearmor -o /etc/apt/keyrings/opentofu-repo.gpg >/dev/null
        sudo chmod a+r /etc/apt/keyrings/opentofu.gpg /etc/apt/keyrings/opentofu-repo.gpg

    - name: Add OpenTofu Repository
      run: |
        echo "deb [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main" | \
        sudo tee /etc/apt/sources.list.d/opentofu.list > /dev/null
        echo "deb-src [signed-by=/etc/apt/keyrings/opentofu.gpg,/etc/apt/keyrings/opentofu-repo.gpg] https://packages.opentofu.org/opentofu/tofu/any/ any main" | \
        sudo tee -a /etc/apt/sources.list.d/opentofu.list > /dev/null
        sudo chmod a+r /etc/apt/sources.list.d/opentofu.list

    - name: Install OpenTofu
      run: |
        sudo apt-get update
        sudo apt-get install -y tofu
        tofu --version # Verify installation

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: OpenTofu Init
      run: tofu init

    - name: OpenTofu Plan
      run: tofu plan
      if: github.event_name == 'pull_request'